/* @pjs pauseOnBlur="true";
        font="../assets/mario/fonts/acmesa.ttf";
        preload="../assets/mario/graphics/backgrounds/ground-filler.gif,
                 ../assets/mario/graphics/backgrounds/ground-slant.gif,
                 ../assets/mario/graphics/backgrounds/ground-top.gif,

                 ../assets/mario/graphics/backgrounds/ground-corner-left.gif,
                 ../assets/mario/graphics/backgrounds/ground-corner-right.gif,
                 ../assets/mario/graphics/backgrounds/ground-side-left.gif,
                 ../assets/mario/graphics/backgrounds/ground-side-right.gif,

                 ../assets/mario/graphics/backgrounds/sky.gif,
                 ../assets/mario/graphics/backgrounds/bush-01.gif,
                 ../assets/mario/graphics/backgrounds/bush-02.gif,
                 ../assets/mario/graphics/backgrounds/bush-03.gif,
                 ../assets/mario/graphics/backgrounds/bush-04.gif,
                 ../assets/mario/graphics/backgrounds/bush-05.gif,

                 ../assets/mario/graphics/assorted/Dragon-coin.gif,
                 ../assets/mario/graphics/assorted/Regular-coin.gif,
                 ../assets/mario/graphics/assorted/Mushroom.gif,
                 ../assets/mario/graphics/assorted/Block.gif,
                 ../assets/mario/graphics/assorted/Coin-block.gif,
                 ../assets/mario/graphics/assorted/Coin-block-exhausted.gif,
                 ../assets/mario/graphics/assorted/Passthrough-block.gif,
                 ../assets/mario/graphics/assorted/Goal-front.gif,
                 ../assets/mario/graphics/assorted/Goal-back.gif,
                 ../assets/mario/graphics/assorted/Goal-slider.gif,

                 ../assets/mario/graphics/enemies/Dead-koopa.gif,
                 ../assets/mario/graphics/enemies/Naked-koopa-walking.gif,
                 ../assets/mario/graphics/enemies/Red-koopa-walking.gif,
                 ../assets/mario/graphics/enemies/Red-koopa-standing.gif,
                 ../assets/mario/graphics/enemies/Red-koopa-flying.gif,
                 ../assets/mario/graphics/enemies/Banzai-bill.gif,

                 ../assets/mario/graphics/mario/small/Crouching-mario.gif,
                 ../assets/mario/graphics/mario/small/Dead-mario.gif,
                 ../assets/mario/graphics/mario/small/Jumping-mario.gif,
                 ../assets/mario/graphics/mario/small/Looking-mario.gif,
                 ../assets/mario/graphics/mario/small/Running-mario.gif,
                 ../assets/mario/graphics/mario/small/Spinning-mario.gif,
                 ../assets/mario/graphics/mario/small/Standing-mario.gif,

                 ../assets/mario/graphics/mario/big/Crouching-mario.gif,
                 ../assets/mario/graphics/mario/big/Dead-mario.gif,
                 ../assets/mario/graphics/mario/big/Jumping-mario.gif,
                 ../assets/mario/graphics/mario/big/Looking-mario.gif,
                 ../assets/mario/graphics/mario/big/Running-mario.gif,
                 ../assets/mario/graphics/mario/big/Spinning-mario.gif,
                 ../assets/mario/graphics/mario/big/Standing-mario.gif"; */
